/*
 * IndexPathForm.java
 * Created on __DATE__, __TIME__
 */

package com.metarnet.luene;

import javax.swing.JOptionPane;
import javax.swing.JTextField;
import javax.swing.table.DefaultTableModel;

import com.metarnet.component.ButtonEditor;
import com.metarnet.component.ButtonRenderer;
import com.metarnet.component.SwingEditDeal;

/**
 * @author __USER__
 */
public class IndexPathForm extends javax.swing.JFrame implements SwingEditDeal
{

	private static final long serialVersionUID = - 6698603362475419931L;

	public String luceneConfig;

	private String head[] = new String [] { "路径", "操作" };

	private Object [][] tableData = null;

	private DealXML dealXML;

	/** Creates new form IndexPathForm */
	public IndexPathForm( String luceneConfig )
	{
		initComponents();
		this.luceneConfig = luceneConfig;
		myInit();
	}

	public void myInit()
	{
		dealXML = new DealXML();
		dealXML.check( luceneConfig );
	}

	public void initTable()
	{
		String [] pathArray = dealXML.read( luceneConfig ).toArray( new String [ 0 ] );
		tableData = transTableData( pathArray );
		DefaultTableModel defaultTableModel = new DefaultTableModel( tableData , head );
		ButtonEditor buttonEditor = new ButtonEditor( new JTextField() );
		buttonEditor.setDeal( this );
		jTablePathIndex.setModel( defaultTableModel );
		jTablePathIndex.getColumnModel().getColumn( 0 ).setPreferredWidth( 289 );
		jTablePathIndex.getColumnModel().getColumn( 1 ).setCellRenderer( new ButtonRenderer() );
		jTablePathIndex.getColumnModel().getColumn( 1 ).setCellEditor( buttonEditor );
		// jTablePathIndex.setAutoResizeMode( JTable.AUTO_RESIZE_OFF );
	}

	@Override
	public void dealSwingEdit( Object obj )
	{
		int result = JOptionPane.showConfirmDialog( null , "您确认删除这个目录？" , "删除目录" , JOptionPane.OK_CANCEL_OPTION );
		if ( result == JOptionPane.OK_OPTION )
		{
			int row = Integer.parseInt( obj.toString() );
			dealXML.delete( luceneConfig , tableData[ row ][ 0 ].toString() );

			initTable();
		}
	}

	public Object [][] transTableData( String [] pathArray )
	{
		Object [][] obj = new Object [ pathArray.length ] [ 2 ];
		for( int i = 0 ; i < pathArray.length ; i ++ )
		{
			obj[ i ][ 0 ] = pathArray[ i ];
			obj[ i ][ 1 ] = "删除";
		}
		return obj;
	}

	/**
	 * This method is called from within the constructor to
	 * initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is
	 * always regenerated by the Form Editor.
	 */
	//GEN-BEGIN:initComponents
	// <editor-fold defaultstate="collapsed" desc="Generated Code">
	private void initComponents()
	{

		jLabel1 = new javax.swing.JLabel();
		jScrollPane1 = new javax.swing.JScrollPane();
		jTablePathIndex = new javax.swing.JTable();
		jButton1 = new javax.swing.JButton();
		jScrollPane2 = new javax.swing.JScrollPane();
		jTextAreaInfo = new javax.swing.JTextArea();

		jLabel1.setText( "\u5df2\u7ecf\u7eb3\u5165\u7d22\u5f15\u7684\u8def\u5f84\uff1a" );

		jTablePathIndex.setModel( new javax.swing.table.DefaultTableModel( new Object [] [] { { null, null, null, null }, { null, null, null, null }, { null, null, null, null },
				{ null, null, null, null } } , new String [] { "Title 1", "Title 2", "Title 3", "Title 4" } ) );
		jScrollPane1.setViewportView( jTablePathIndex );

		jButton1.setText( "\u5237\u65b0" );

		jTextAreaInfo.setColumns( 20 );
		jTextAreaInfo.setRows( 5 );
		jScrollPane2.setViewportView( jTextAreaInfo );

		javax.swing.GroupLayout layout = new javax.swing.GroupLayout( getContentPane() );
		getContentPane().setLayout( layout );
		layout.setHorizontalGroup( layout
				.createParallelGroup( javax.swing.GroupLayout.Alignment.LEADING )
				.addGroup( layout.createSequentialGroup().addContainerGap().addComponent( jLabel1 ).addContainerGap( 268 , Short.MAX_VALUE ) )
				.addGroup(
						javax.swing.GroupLayout.Alignment.TRAILING ,
						layout.createSequentialGroup()
								.addContainerGap()
								.addGroup(
										layout.createParallelGroup( javax.swing.GroupLayout.Alignment.TRAILING , false ).addComponent( jScrollPane2 , javax.swing.GroupLayout.Alignment.LEADING )
												.addComponent( jButton1 , javax.swing.GroupLayout.Alignment.LEADING )
												.addComponent( jScrollPane1 , javax.swing.GroupLayout.DEFAULT_SIZE , 357 , Short.MAX_VALUE ) ).addGap( 31 , 31 , 31 ) ) );
		layout.setVerticalGroup( layout.createParallelGroup( javax.swing.GroupLayout.Alignment.LEADING ).addGroup(
				layout.createSequentialGroup().addContainerGap().addComponent( jLabel1 ).addPreferredGap( javax.swing.LayoutStyle.ComponentPlacement.RELATED )
						.addComponent( jScrollPane1 , javax.swing.GroupLayout.PREFERRED_SIZE , 155 , javax.swing.GroupLayout.PREFERRED_SIZE )
						.addPreferredGap( javax.swing.LayoutStyle.ComponentPlacement.UNRELATED ).addComponent( jButton1 ).addPreferredGap( javax.swing.LayoutStyle.ComponentPlacement.RELATED )
						.addComponent( jScrollPane2 , javax.swing.GroupLayout.PREFERRED_SIZE , javax.swing.GroupLayout.DEFAULT_SIZE , javax.swing.GroupLayout.PREFERRED_SIZE )
						.addContainerGap( javax.swing.GroupLayout.DEFAULT_SIZE , Short.MAX_VALUE ) ) );

		pack();
	}// </editor-fold>
	//GEN-END:initComponents

	/**
	 * @param args the command line arguments
	 */
	public static void main( String args[] )
	{
		java.awt.EventQueue.invokeLater( new Runnable()
		{
			public void run()
			{
				// new IndexPathForm().setVisible( true );
			}
		} );
	}

	//GEN-BEGIN:variables
	// Variables declaration - do not modify
	private javax.swing.JButton jButton1;

	private javax.swing.JLabel jLabel1;

	private javax.swing.JScrollPane jScrollPane1;

	private javax.swing.JScrollPane jScrollPane2;

	private javax.swing.JTable jTablePathIndex;

	private javax.swing.JTextArea jTextAreaInfo;
	// End of variables declaration//GEN-END:variables

}
