/*
 * SendMsg.java
 * Created on __DATE__, __TIME__
 */

package com.metarnet.jmstool;

import java.util.Arrays;
import java.util.HashMap;
import java.util.Iterator;
import java.util.Map;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;
import javax.swing.JOptionPane;

import com.metarnet.msg.SendMessage;
import com.metarnet.recmsg.ReadExcel;

/**
 * @author __USER__
 */
public class SendMsg extends javax.swing.JPanel
{

	private static final long serialVersionUID = 6747822658671077053L;

	private Map<String,MsgDefault> msgDefaultMap;

	private String head[] = new String [] { "含义", "属性名称", "属性值" };

	private String default_title_ch = "自定义";

	private ReadExcel readExcel;

	boolean allowSend = true;

	private SendMessage sendMessage;

	private Thread sendThread;

	/** Creates new form SendMsg */
	public SendMsg()
	{
		initComponents();
		myInit();
	}

	public MsgDefault defaultTableValue()
	{
		MsgDefault msgDefault = new MsgDefault( "default" , default_title_ch , MsgDefault.MSG_TYPE_TEXT );

		for( int i = 0 ; i < 19 ; i ++ )
		{
			msgDefault.addPro( null , null , null );
		}

		return msgDefault;
	}

	public void myInit()
	{
		// //////////////////////////

		jLabelMsgType.setVisible( false );

		// //////////////////////////

		Object [][] value = defaultTableValue().toObjects();
		DefaultTableModel defaultTableModel = new DefaultTableModel( value , head );
		jTableData.setModel( defaultTableModel );

		// //////////////////////////

		readExcel = new ReadExcel();

		msgDefaultMap = readExcel.read();

		String msgDefaultArray[] = new String [ msgDefaultMap.size() + 1 ];// 0留給默認

		Iterator<String> iterator = msgDefaultMap.keySet().iterator();

		msgDefaultArray[ 0 ] = default_title_ch;

		for( int i = 1 ; i < msgDefaultMap.size() + 1 ; i ++ )
		{
			msgDefaultArray[ i ] = msgDefaultMap.get( iterator.next() ).getTitle_ch();
		}

		Arrays.sort( msgDefaultArray );

		jComboBoxWaitLoad.setModel( new javax.swing.DefaultComboBoxModel( msgDefaultArray ) );

		msgDefaultMap.put( default_title_ch , defaultTableValue() );
	}

	/**
	 * This method is called from within the constructor to
	 * initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is
	 * always regenerated by the Form Editor.
	 */
	// GEN-BEGIN:initComponents
	// <editor-fold defaultstate="collapsed" desc="Generated Code">
	private void initComponents()
	{

		jLabel3 = new javax.swing.JLabel();
		jLabel4 = new javax.swing.JLabel();
		jTextFieldIp = new javax.swing.JTextField();
		jTextFieldPort = new javax.swing.JTextField();
		jButtonSend = new javax.swing.JButton();
		jLabel1 = new javax.swing.JLabel();
		jTextFieldTopicname = new javax.swing.JTextField();
		jScrollPane1 = new javax.swing.JScrollPane();
		jTableData = new javax.swing.JTable();
		jComboBoxWaitLoad = new javax.swing.JComboBox();
		jButtonLoad = new javax.swing.JButton();
		jLabelMsgType = new javax.swing.JLabel();
		jLabel2 = new javax.swing.JLabel();
		jTextFieldTime = new javax.swing.JTextField();
		jLabel5 = new javax.swing.JLabel();
		jTextFieldSendGap = new javax.swing.JTextField();
		jButtonStop = new javax.swing.JButton();
		jTextFieldSendCount = new javax.swing.JTextField();
		jLabel6 = new javax.swing.JLabel();

		jLabel3.setText( "IP\u5730\u5740\uff1a" );

		jLabel4.setText( "\u7aef\u53e3\u53f7\uff1a" );

		jTextFieldIp.setText( "192.168.29.27" );

		jTextFieldPort.setText( "61616" );

		jButtonSend.setText( "\u53d1\u9001\u6570\u636e" );
		jButtonSend.addMouseListener( new java.awt.event.MouseAdapter()
		{
			public void mouseReleased( java.awt.event.MouseEvent evt )
			{
				jButtonSendMouseReleased( evt );
			}
		} );

		jLabel1.setText( "\u4e3b\u9898\uff1a" );

		jTableData.setModel( new javax.swing.table.DefaultTableModel(
				new Object [] [] { { null, null, null, null }, { null, null, null, null }, { null, null, null, null }, { null, null, null, null } } , new String [] { "Title 1", "Title 2", "Title 3",
						"Title 4" } ) );
		jScrollPane1.setViewportView( jTableData );

		jComboBoxWaitLoad.setModel( new javax.swing.DefaultComboBoxModel( new String [] { "Item 1", "Item 2", "Item 3", "Item 4" } ) );

		jButtonLoad.setText( "\u52a0\u8f7d" );
		jButtonLoad.addMouseListener( new java.awt.event.MouseAdapter()
		{
			public void mouseReleased( java.awt.event.MouseEvent evt )
			{
				jButtonLoadMouseReleased( evt );
			}
		} );
		jButtonLoad.addActionListener( new java.awt.event.ActionListener()
		{
			public void actionPerformed( java.awt.event.ActionEvent evt )
			{
				jButtonLoadActionPerformed( evt );
			}
		} );

		jLabelMsgType.setText( "0" );

		jLabel2.setText( "\u53d1\u9001\u6b21\u6570\uff1a" );

		jTextFieldTime.setText( "1" );

		jLabel5.setText( "\u53d1\u9001\u95f4\u9694(\u6beb\u79d2)\uff1a" );

		jTextFieldSendGap.setText( "1000" );

		jButtonStop.setText( "\u505c\u6b62\u53d1\u9001" );
		jButtonStop.setEnabled( false );
		jButtonStop.addMouseListener( new java.awt.event.MouseAdapter()
		{
			public void mouseReleased( java.awt.event.MouseEvent evt )
			{
				jButtonStopMouseReleased( evt );
			}
		} );
		jButtonStop.addActionListener( new java.awt.event.ActionListener()
		{
			public void actionPerformed( java.awt.event.ActionEvent evt )
			{
				jButtonStopActionPerformed( evt );
			}
		} );

		jTextFieldSendCount.setText( "0" );

		jLabel6.setText( "\u5df2\u53d1\u9001\uff1a" );

		javax.swing.GroupLayout layout = new javax.swing.GroupLayout( this );
		this.setLayout( layout );
		layout.setHorizontalGroup( layout
				.createParallelGroup( javax.swing.GroupLayout.Alignment.LEADING )
				.addGroup(
						layout.createSequentialGroup().addContainerGap().addComponent( jLabel2 ).addGap( 6 , 6 , 6 )
								.addComponent( jTextFieldTime , javax.swing.GroupLayout.PREFERRED_SIZE , 77 , javax.swing.GroupLayout.PREFERRED_SIZE ).addGap( 27 , 27 , 27 ).addComponent( jLabel5 )
								.addPreferredGap( javax.swing.LayoutStyle.ComponentPlacement.RELATED )
								.addComponent( jTextFieldSendGap , javax.swing.GroupLayout.PREFERRED_SIZE , 64 , javax.swing.GroupLayout.PREFERRED_SIZE )
								.addPreferredGap( javax.swing.LayoutStyle.ComponentPlacement.RELATED , 36 , Short.MAX_VALUE ).addComponent( jLabel6 )
								.addPreferredGap( javax.swing.LayoutStyle.ComponentPlacement.RELATED )
								.addComponent( jTextFieldSendCount , javax.swing.GroupLayout.PREFERRED_SIZE , 90 , javax.swing.GroupLayout.PREFERRED_SIZE ).addGap( 91 , 91 , 91 ) )
				.addGroup(
						javax.swing.GroupLayout.Alignment.TRAILING ,
						layout.createSequentialGroup()
								.addGroup(
										layout.createParallelGroup( javax.swing.GroupLayout.Alignment.TRAILING )
												.addGroup( javax.swing.GroupLayout.Alignment.LEADING ,
														layout.createSequentialGroup().addContainerGap().addComponent( jScrollPane1 , javax.swing.GroupLayout.DEFAULT_SIZE , 510 , Short.MAX_VALUE ) )
												.addGroup(
														layout.createSequentialGroup().addContainerGap()
																.addComponent( jComboBoxWaitLoad , javax.swing.GroupLayout.PREFERRED_SIZE , 242 , javax.swing.GroupLayout.PREFERRED_SIZE )
																.addPreferredGap( javax.swing.LayoutStyle.ComponentPlacement.RELATED ).addComponent( jButtonLoad )
																.addPreferredGap( javax.swing.LayoutStyle.ComponentPlacement.RELATED , 24 , Short.MAX_VALUE ).addComponent( jButtonStop )
																.addGap( 18 , 18 , 18 ).addComponent( jButtonSend ) )
												.addGroup(
														layout.createSequentialGroup().addGap( 22 , 22 , 22 ).addComponent( jLabel3 )
																.addPreferredGap( javax.swing.LayoutStyle.ComponentPlacement.UNRELATED )
																.addComponent( jTextFieldIp , javax.swing.GroupLayout.PREFERRED_SIZE , 109 , javax.swing.GroupLayout.PREFERRED_SIZE )
																.addPreferredGap( javax.swing.LayoutStyle.ComponentPlacement.UNRELATED ).addComponent( jLabel4 )
																.addPreferredGap( javax.swing.LayoutStyle.ComponentPlacement.RELATED )
																.addComponent( jTextFieldPort , javax.swing.GroupLayout.PREFERRED_SIZE , 55 , javax.swing.GroupLayout.PREFERRED_SIZE )
																.addGap( 32 , 32 , 32 ).addComponent( jLabel1 ).addGap( 18 , 18 , 18 )
																.addComponent( jTextFieldTopicname , javax.swing.GroupLayout.DEFAULT_SIZE , 126 , Short.MAX_VALUE ) ) ).addGap( 18 , 18 , 18 )
								.addComponent( jLabelMsgType ).addGap( 73 , 73 , 73 ) ) );
		layout.setVerticalGroup( layout.createParallelGroup( javax.swing.GroupLayout.Alignment.LEADING ).addGroup(
				layout.createSequentialGroup()
						.addGap( 22 , 22 , 22 )
						.addGroup(
								layout.createParallelGroup( javax.swing.GroupLayout.Alignment.BASELINE ).addComponent( jLabel3 ).addComponent( jLabel4 )
										.addComponent( jTextFieldPort , javax.swing.GroupLayout.PREFERRED_SIZE , javax.swing.GroupLayout.DEFAULT_SIZE , javax.swing.GroupLayout.PREFERRED_SIZE )
										.addComponent( jLabel1 )
										.addComponent( jTextFieldTopicname , javax.swing.GroupLayout.PREFERRED_SIZE , javax.swing.GroupLayout.DEFAULT_SIZE , javax.swing.GroupLayout.PREFERRED_SIZE )
										.addComponent( jLabelMsgType )
										.addComponent( jTextFieldIp , javax.swing.GroupLayout.PREFERRED_SIZE , javax.swing.GroupLayout.DEFAULT_SIZE , javax.swing.GroupLayout.PREFERRED_SIZE ) )
						.addPreferredGap( javax.swing.LayoutStyle.ComponentPlacement.UNRELATED )
						.addGroup(
								layout.createParallelGroup( javax.swing.GroupLayout.Alignment.BASELINE ).addComponent( jLabel2 )
										.addComponent( jTextFieldTime , javax.swing.GroupLayout.PREFERRED_SIZE , javax.swing.GroupLayout.DEFAULT_SIZE , javax.swing.GroupLayout.PREFERRED_SIZE )
										.addComponent( jLabel5 )
										.addComponent( jTextFieldSendGap , javax.swing.GroupLayout.PREFERRED_SIZE , javax.swing.GroupLayout.DEFAULT_SIZE , javax.swing.GroupLayout.PREFERRED_SIZE )
										.addComponent( jLabel6 )
										.addComponent( jTextFieldSendCount , javax.swing.GroupLayout.PREFERRED_SIZE , javax.swing.GroupLayout.DEFAULT_SIZE , javax.swing.GroupLayout.PREFERRED_SIZE ) )
						.addGap( 6 , 6 , 6 )
						.addGroup(
								layout.createParallelGroup( javax.swing.GroupLayout.Alignment.BASELINE ).addComponent( jButtonLoad )
										.addComponent( jComboBoxWaitLoad , javax.swing.GroupLayout.PREFERRED_SIZE , javax.swing.GroupLayout.DEFAULT_SIZE , javax.swing.GroupLayout.PREFERRED_SIZE )
										.addComponent( jButtonSend ).addComponent( jButtonStop ) ).addPreferredGap( javax.swing.LayoutStyle.ComponentPlacement.RELATED )
						.addComponent( jScrollPane1 , javax.swing.GroupLayout.PREFERRED_SIZE , 351 , javax.swing.GroupLayout.PREFERRED_SIZE ).addContainerGap( 50 , Short.MAX_VALUE ) ) );
	}// </editor-fold>
		// GEN-END:initComponents

	private void jButtonStopActionPerformed( java.awt.event.ActionEvent evt )
	{
		// TODO add your handling code here:
	}

	private void jButtonStopMouseReleased( java.awt.event.MouseEvent evt )
	{
		allowSend = false;
		jButtonSend.setEnabled( true );
		jButtonStop.setEnabled( false );
		if ( sendMessage != null )
		{
			sendMessage.setAllowSend( false );
		}
	}

	private void jButtonLoadActionPerformed( java.awt.event.ActionEvent evt )
	{
		// TODO add your handling code here:
	}

	private void jButtonLoadMouseReleased( java.awt.event.MouseEvent evt )
	{
		print( "in jButtonLoadMouseReleased" );

		String selected = jComboBoxWaitLoad.getSelectedItem().toString();

		print( selected );

		MsgDefault msgDefault = readExcel.readSheet( selected );

		if ( selected.equals( default_title_ch ) )
		{
			msgDefault = defaultTableValue();
		}

		jTableData.setModel( new javax.swing.table.DefaultTableModel( msgDefault.toObjects() , head ) );

		if ( selected.equals( default_title_ch ) )
		{
			jTextFieldTopicname.setText( "" );
			jLabelMsgType.setText( MsgDefault.MSG_TYPE_TEXT + "" );
		}
		else
		{
			jTextFieldTopicname.setText( msgDefault.getTitle() );
			jLabelMsgType.setText( msgDefault.getMsgType() + "" );
		}

	}

	private void jButtonSendMouseReleased( java.awt.event.MouseEvent evt )
	{
		print( "in jButtonSendMouseReleased" );

		allowSend = true;
		jButtonSend.setEnabled( false );
		jButtonStop.setEnabled( true );

		TableModel tm = jTableData.getModel();

		Map<String,String> dataMap = new HashMap<String,String>();
		for( int i = 0 ; i < tm.getRowCount() ; i ++ )
		{
			String proName = nullToEmpty( tm.getValueAt( i , 1 ) );
			String proValue = nullToEmpty( tm.getValueAt( i , 2 ) );
			if ( ! proName.equals( "" ) && ! proValue.equals( "" ) )
			{
				dataMap.put( proName , proValue );
			}
		}

		int port = Integer.parseInt( jTextFieldPort.getText() );
		String ip = jTextFieldIp.getText();
		String topicname = jTextFieldTopicname.getText();
		int time = Integer.parseInt( jTextFieldTime.getText() );
		int sendGap = Integer.parseInt( jTextFieldSendGap.getText() );

		if ( ! "".equals( topicname ) && ! dataMap.isEmpty() )
		{
			int msgType = Integer.parseInt( jLabelMsgType.getText() );

			sendMessage = new SendMessage( ip , port , topicname , dataMap , msgType , time , sendGap , this );
			sendMessage.setAllowSend( true );
			sendThread = new Thread( sendMessage );
			sendThread.start();

		}
		else
		{
			JOptionPane.showMessageDialog( this , "主題及數據不能為空." );
		}

	}

	public void addSendCount()
	{
		String countStr = jTextFieldSendCount.getText();
		int count = 0;
		if( countStr!=null && !countStr.equals( "" ))
		{
			count = Integer.parseInt( countStr );
		}
		jTextFieldSendCount.setText( ++ count + "" );
	}

	public void enableSend()
	{
		jButtonSend.setEnabled( true );
		jButtonStop.setEnabled( false );
	}

	public String nullToEmpty( Object s )
	{
		return s == null ? "" : s.toString();
	}

	public void showInfo( String info )
	{
		JOptionPane.showMessageDialog( this , info );
	}

	public void print( String s )
	{
		System.out.println( s );
	}

	// GEN-BEGIN:variables
	// Variables declaration - do not modify
	private javax.swing.JButton jButtonLoad;

	private javax.swing.JButton jButtonSend;

	private javax.swing.JButton jButtonStop;

	private javax.swing.JComboBox jComboBoxWaitLoad;

	private javax.swing.JLabel jLabel1;

	private javax.swing.JLabel jLabel2;

	private javax.swing.JLabel jLabel3;

	private javax.swing.JLabel jLabel4;

	private javax.swing.JLabel jLabel5;

	private javax.swing.JLabel jLabel6;

	private javax.swing.JLabel jLabelMsgType;

	private javax.swing.JScrollPane jScrollPane1;

	private javax.swing.JTable jTableData;

	private javax.swing.JTextField jTextFieldIp;

	private javax.swing.JTextField jTextFieldPort;

	private javax.swing.JTextField jTextFieldSendCount;

	private javax.swing.JTextField jTextFieldSendGap;

	private javax.swing.JTextField jTextFieldTime;

	private javax.swing.JTextField jTextFieldTopicname;
	// End of variables declaration//GEN-END:variables

}
